# Generated by Django 3.0.5 on 2023-09-07 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hallticket', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hallticket',
            name='examination_date',
        ),
        migrations.RemoveField(
            model_name='hallticket',
            name='student',
        ),
    ]
