# Generated by Django 3.0.5 on 2023-09-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hallticket', '0007_auto_20230910_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
