# Generated by Django 3.0.5 on 2023-09-10 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hallticket', '0009_auto_20230910_1029'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
