# Generated by Django 3.0.5 on 2023-09-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hallticket', '0011_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
