# Generated by Django 3.0.5 on 2023-09-11 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hallticket', '0013_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
