# Generated by Django 3.0.5 on 2023-09-14 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hallticket', '0014_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='hallticket',
            name='student',
            field=models.OneToOneField(default='user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
