# Generated by Django 3.0.5 on 2023-09-10 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20230908_2129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='enrollment_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='student_name',
        ),
    ]
