# Generated by Django 3.0.5 on 2023-09-10 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20230910_1034'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='enrollment_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='student_name',
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('aadhaar_number', models.CharField(max_length=12)),
                ('program', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('enrollment_number', models.CharField(max_length=20, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
