# Generated by Django 3.0.5 on 2023-09-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='enrollment_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='student_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
