# Generated by Django 3.0.5 on 2023-09-11 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20230910_1948'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
