# Generated by Django 3.0.5 on 2023-09-11 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20230911_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='aadhaar_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='course',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='program',
        ),
        migrations.AddField(
            model_name='student',
            name='aadhaar_number',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='enrollment_number',
            field=models.CharField(default=123, max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='student_name',
            field=models.CharField(default='abc', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
    ]
