# Generated by Django 3.0.5 on 2023-09-12 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20230912_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='enrollment_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='student_name',
        ),
    ]
